apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: nodeapp
  strategy: {}
  template:
    metadata:
      labels:
        run: nodeapp
    spec:
      containers:
      - image: gcr.io/arctic-pad-352111/nodeapp:v1
        name: nodeapp
        ports:
        - containerPort: 3000
          protocol: TCP 

---

apiVersion: v1
kind: Service
metadata:
  name: secure-nodeapp
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    name: http
  selector:
    run: nodeapp
  type: NodePort

---
